/**
 * Drizzle schema — the single source of truth for the z-freelance data model.
 *
 * Conventions
 * -----------
 * - Primary keys are UUIDs generated by the database (`gen_random_uuid()` on
 *   Postgres, `uuid_generate_v4()` fallback is unnecessary on PG >= 13).
 * - Money is always stored as integer minor units (cents) in `bigint` columns.
 *   Never store floats for currency — see `src/lib/money.ts`.
 * - Timestamps are `timestamptz` and always populated by the database.
 * - Status columns are Postgres enums so invalid states are impossible at the
 *   storage layer, not merely discouraged at the application layer.
 */
import { sql } from "drizzle-orm";
import {
  bigint,
  check,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
  varchar,
} from "drizzle-orm/pg-core";

/* ------------------------------------------------------------------ enums */

export const userRoleEnum = pgEnum("user_role", ["CLIENT", "FREELANCER", "ADMIN"]);
export const userStatusEnum = pgEnum("user_status", ["ACTIVE", "SUSPENDED"]);
export const availabilityEnum = pgEnum("availability", ["AVAILABLE", "BUSY", "UNAVAILABLE"]);
export const budgetTypeEnum = pgEnum("budget_type", ["FIXED", "HOURLY"]);
export const experienceLevelEnum = pgEnum("experience_level", ["ENTRY", "INTERMEDIATE", "EXPERT"]);
export const projectStatusEnum = pgEnum("project_status", [
  "DRAFT",
  "OPEN",
  "IN_PROGRESS",
  "CLOSED",
  "CANCELLED",
]);
export const proposalStatusEnum = pgEnum("proposal_status", [
  "PENDING",
  "SHORTLISTED",
  "REJECTED",
  "WITHDRAWN",
  "HIRED",
]);
export const contractStatusEnum = pgEnum("contract_status", [
  "ACTIVE",
  "COMPLETED",
  "CANCELLED",
  "DISPUTED",
]);
export const milestoneStatusEnum = pgEnum("milestone_status", [
  // PENDING   -> created, awaiting client funding
  // FUNDED    -> money is held in escrow
  // SUBMITTED -> freelancer delivered the work
  // RELEASED  -> escrow released to the freelancer (fee deducted)
  // DISPUTED  -> held pending an admin decision
  // REFUNDED  -> returned to the client after a dispute
  "PENDING",
  "FUNDED",
  "SUBMITTED",
  "RELEASED",
  "DISPUTED",
  "REFUNDED",
]);
export const transactionTypeEnum = pgEnum("transaction_type", [
  "ESCROW_DEPOSIT",
  "ESCROW_RELEASE",
  "PLATFORM_FEE",
  "PAYOUT",
  "REFUND",
]);
export const transactionStatusEnum = pgEnum("transaction_status", ["PENDING", "SETTLED", "FAILED"]);
export const payoutStatusEnum = pgEnum("payout_status", [
  "REQUESTED",
  "PROCESSING",
  "PAID",
  "FAILED",
]);
export const reviewDirectionEnum = pgEnum("review_direction", [
  "CLIENT_TO_FREELANCER",
  "FREELANCER_TO_CLIENT",
]);
export const attachmentContextEnum = pgEnum("attachment_context", [
  "MESSAGE",
  "MILESTONE",
  "PORTFOLIO",
]);
export const disputeStatusEnum = pgEnum("dispute_status", [
  "OPEN",
  "IN_REVIEW",
  "RESOLVED_CLIENT",
  "RESOLVED_FREELANCER",
  "WITHDRAWN",
]);
export const notificationTypeEnum = pgEnum("notification_type", [
  "PROJECT_PUBLISHED",
  "PROPOSAL_RECEIVED",
  "PROPOSAL_SHORTLISTED",
  "PROPOSAL_REJECTED",
  "PROPOSAL_WITHDRAWN",
  "CONTRACT_STARTED",
  "MILESTONE_FUNDED",
  "WORK_SUBMITTED",
  "MILESTONE_APPROVED",
  "DISPUTE_OPENED",
  "DISPUTE_RESOLVED",
  "MESSAGE_RECEIVED",
  "REVIEW_RECEIVED",
  "ACCOUNT_SUSPENDED",
  "PAYOUT_PAID",
]);

/* ------------------------------------------------------------- identities */

export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    email: varchar("email", { length: 254 }).notNull(),
    passwordHash: text("password_hash").notNull(),
    name: varchar("name", { length: 120 }).notNull(),
    role: userRoleEnum("role").notNull().default("CLIENT"),
    status: userStatusEnum("status").notNull().default("ACTIVE"),
    avatarUrl: text("avatar_url"),
    /**
     * Per-type in-app notification opt-outs: `{ "MESSAGE_RECEIVED": false }`
     * means "don't create message notifications". Missing keys mean enabled.
     */
    notificationPrefs: jsonb("notification_prefs").$type<Record<string, boolean>>(),
    /**
     * When set, session tokens issued BEFORE this instant are rejected.
     * Bumped on password change and administrative suspension.
     */
    sessionsInvalidatedAt: timestamp("sessions_invalidated_at", { withTimezone: true }),
    emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
    lastLoginAt: timestamp("last_login_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    emailUnique: uniqueIndex("users_email_unique").on(t.email),
    roleIdx: index("users_role_idx").on(t.role),
    statusIdx: index("users_status_idx").on(t.status),
  }),
);

export const freelancerProfiles = pgTable(
  "freelancer_profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    headline: varchar("headline", { length: 160 }),
    bio: text("bio"),
    hourlyRateCents: bigint("hourly_rate_cents", { mode: "number" }),
    country: varchar("country", { length: 80 }),
    city: varchar("city", { length: 80 }),
    availability: availabilityEnum("availability").notNull().default("AVAILABLE"),
    yearsExperience: integer("years_experience").notNull().default(0),
    portfolioUrl: text("portfolio_url"),
    githubUrl: text("github_url"),
    linkedinUrl: text("linkedin_url"),
    ratingAvg: numeric("rating_avg", { precision: 3, scale: 2, mode: "number" })
      .notNull()
      .default(0),
    ratingCount: integer("rating_count").notNull().default(0),
    completedContracts: integer("completed_contracts").notNull().default(0),
    totalEarnedCents: bigint("total_earned_cents", { mode: "number" }).notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userUnique: uniqueIndex("freelancer_profiles_user_id_unique").on(t.userId),
    rateIdx: index("freelancer_profiles_rate_idx").on(t.hourlyRateCents),
    ratingIdx: index("freelancer_profiles_rating_idx").on(t.ratingAvg),
  }),
);

export const clientProfiles = pgTable(
  "client_profiles",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    companyName: varchar("company_name", { length: 160 }),
    website: text("website"),
    bio: text("bio"),
    country: varchar("country", { length: 80 }),
    city: varchar("city", { length: 80 }),
    ratingAvg: numeric("rating_avg", { precision: 3, scale: 2, mode: "number" })
      .notNull()
      .default(0),
    ratingCount: integer("rating_count").notNull().default(0),
    totalSpentCents: bigint("total_spent_cents", { mode: "number" }).notNull().default(0),
    projectsPosted: integer("projects_posted").notNull().default(0),
    paymentVerifiedAt: timestamp("payment_verified_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userUnique: uniqueIndex("client_profiles_user_id_unique").on(t.userId),
  }),
);

/* --------------------------------------------------------------- taxonomy */

export const categories = pgTable(
  "categories",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: varchar("name", { length: 80 }).notNull(),
    slug: varchar("slug", { length: 96 }).notNull(),
    description: text("description"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    slugUnique: uniqueIndex("categories_slug_unique").on(t.slug),
  }),
);

export const skills = pgTable(
  "skills",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: varchar("name", { length: 80 }).notNull(),
    slug: varchar("slug", { length: 96 }).notNull(),
    categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }),
  },
  (t) => ({
    slugUnique: uniqueIndex("skills_slug_unique").on(t.slug),
    categoryIdx: index("skills_category_idx").on(t.categoryId),
  }),
);

export const freelancerSkills = pgTable(
  "freelancer_skills",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => freelancerProfiles.id, { onDelete: "cascade" }),
    skillId: uuid("skill_id")
      .notNull()
      .references(() => skills.id, { onDelete: "cascade" }),
    proficiency: integer("proficiency").notNull().default(3),
  },
  (t) => ({
    uniquePair: uniqueIndex("freelancer_skills_profile_skill_unique").on(t.profileId, t.skillId),
  }),
);

/* --------------------------------------------------------------- projects */

export const projects = pgTable(
  "projects",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    clientId: uuid("client_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }),
    title: varchar("title", { length: 160 }).notNull(),
    slug: varchar("slug", { length: 190 }).notNull(),
    description: text("description").notNull(),
    budgetType: budgetTypeEnum("budget_type").notNull().default("FIXED"),
    budgetMinCents: bigint("budget_min_cents", { mode: "number" }),
    budgetMaxCents: bigint("budget_max_cents", { mode: "number" }),
    experienceLevel: experienceLevelEnum("experience_level").notNull().default("INTERMEDIATE"),
    status: projectStatusEnum("status").notNull().default("DRAFT"),
    deadline: timestamp("deadline", { withTimezone: true }),
    proposalsCount: integer("proposals_count").notNull().default(0),
    viewsCount: integer("views_count").notNull().default(0),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    slugUnique: uniqueIndex("projects_slug_unique").on(t.slug),
    clientIdx: index("projects_client_idx").on(t.clientId),
    statusIdx: index("projects_status_idx").on(t.status),
    categoryIdx: index("projects_category_idx").on(t.categoryId),
    publishedIdx: index("projects_published_at_idx").on(t.publishedAt),
    budgetSane: check(
      "projects_budget_range_check",
      // NULL budgets are allowed (undisclosed); when both exist min <= max.
      sql`${t.budgetMinCents} is null or ${t.budgetMaxCents} is null or ${t.budgetMinCents} <= ${t.budgetMaxCents}`,
    ),
  }),
);

export const projectSkills = pgTable(
  "project_skills",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    skillId: uuid("skill_id")
      .notNull()
      .references(() => skills.id, { onDelete: "cascade" }),
  },
  (t) => ({
    uniquePair: uniqueIndex("project_skills_project_skill_unique").on(t.projectId, t.skillId),
  }),
);

/* ------------------------------------------------------------- proposals */

export const proposals = pgTable(
  "proposals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    freelancerId: uuid("freelancer_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    coverLetter: text("cover_letter").notNull(),
    bidAmountCents: bigint("bid_amount_cents", { mode: "number" }).notNull(),
    estimatedDays: integer("estimated_days").notNull().default(7),
    status: proposalStatusEnum("status").notNull().default("PENDING"),
    decidedAt: timestamp("decided_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    onePerProject: uniqueIndex("proposals_project_freelancer_unique").on(
      t.projectId,
      t.freelancerId,
    ),
    freelancerIdx: index("proposals_freelancer_idx").on(t.freelancerId),
    statusIdx: index("proposals_status_idx").on(t.status),
    positiveBid: check("proposals_bid_positive_check", sql`${t.bidAmountCents} > 0`),
  }),
);

/* ------------------------------------------- contracts, escrow and money */

export const contracts = pgTable(
  "contracts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    proposalId: uuid("proposal_id")
      .notNull()
      .references(() => proposals.id, { onDelete: "cascade" }),
    clientId: uuid("client_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    freelancerId: uuid("freelancer_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    title: varchar("title", { length: 160 }).notNull(),
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    platformFeeBps: integer("platform_fee_bps").notNull().default(1000),
    status: contractStatusEnum("status").notNull().default("ACTIVE"),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
    cancelledAt: timestamp("cancelled_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    onePerProposal: uniqueIndex("contracts_proposal_unique").on(t.proposalId),
    clientIdx: index("contracts_client_idx").on(t.clientId),
    freelancerIdx: index("contracts_freelancer_idx").on(t.freelancerId),
    statusIdx: index("contracts_status_idx").on(t.status),
    positiveAmount: check("contracts_amount_positive_check", sql`${t.amountCents} > 0`),
  }),
);

export const milestones = pgTable(
  "milestones",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contractId: uuid("contract_id")
      .notNull()
      .references(() => contracts.id, { onDelete: "cascade" }),
    title: varchar("title", { length: 160 }).notNull(),
    description: text("description"),
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    position: integer("position").notNull().default(1),
    status: milestoneStatusEnum("status").notNull().default("PENDING"),
    dueDate: timestamp("due_date", { withTimezone: true }),
    fundedAt: timestamp("funded_at", { withTimezone: true }),
    submittedAt: timestamp("submitted_at", { withTimezone: true }),
    approvedAt: timestamp("approved_at", { withTimezone: true }),
    releasedAt: timestamp("released_at", { withTimezone: true }),
    submissionNote: text("submission_note"),
    escrowReference: varchar("escrow_reference", { length: 80 }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    contractIdx: index("milestones_contract_idx").on(t.contractId),
    statusIdx: index("milestones_status_idx").on(t.status),
    positiveAmount: check("milestones_amount_positive_check", sql`${t.amountCents} > 0`),
  }),
);

export const wallets = pgTable(
  "wallets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    balanceCents: bigint("balance_cents", { mode: "number" }).notNull().default(0),
    pendingCents: bigint("pending_cents", { mode: "number" }).notNull().default(0),
    currency: varchar("currency", { length: 3 }).notNull().default("USD"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userUnique: uniqueIndex("wallets_user_id_unique").on(t.userId),
    nonNegative: check("wallets_balance_non_negative_check", sql`${t.balanceCents} >= 0`),
  }),
);

export const transactions = pgTable(
  "transactions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    contractId: uuid("contract_id").references(() => contracts.id, { onDelete: "set null" }),
    milestoneId: uuid("milestone_id").references(() => milestones.id, { onDelete: "set null" }),
    type: transactionTypeEnum("type").notNull(),
    status: transactionStatusEnum("status").notNull().default("SETTLED"),
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    currency: varchar("currency", { length: 3 }).notNull().default("USD"),
    reference: varchar("reference", { length: 80 }),
    meta: jsonb("meta"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userIdx: index("transactions_user_idx").on(t.userId),
    typeIdx: index("transactions_type_idx").on(t.type),
    contractIdx: index("transactions_contract_idx").on(t.contractId),
  }),
);

export const payouts = pgTable(
  "payouts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    freelancerId: uuid("freelancer_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
    status: payoutStatusEnum("status").notNull().default("REQUESTED"),
    method: varchar("method", { length: 40 }).notNull().default("BANK_TRANSFER"),
    reference: varchar("reference", { length: 80 }),
    failureReason: text("failure_reason"),
    requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
    paidAt: timestamp("paid_at", { withTimezone: true }),
  },
  (t) => ({
    freelancerIdx: index("payouts_freelancer_idx").on(t.freelancerId),
    statusIdx: index("payouts_status_idx").on(t.status),
  }),
);

/* -------------------------------------------------------------- messaging */

export const threads = pgTable(
  "threads",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contractId: uuid("contract_id").references(() => contracts.id, { onDelete: "cascade" }),
    proposalId: uuid("proposal_id").references(() => proposals.id, { onDelete: "cascade" }),
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
    participantAId: uuid("participant_a_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    participantBId: uuid("participant_b_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    subject: varchar("subject", { length: 160 }).notNull(),
    lastMessageAt: timestamp("last_message_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    aIdx: index("threads_participant_a_idx").on(t.participantAId),
    bIdx: index("threads_participant_b_idx").on(t.participantBId),
  }),
);

export const messages = pgTable(
  "messages",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    threadId: uuid("thread_id")
      .notNull()
      .references(() => threads.id, { onDelete: "cascade" }),
    senderId: uuid("sender_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    body: text("body").notNull(),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    threadIdx: index("messages_thread_idx").on(t.threadId),
    senderIdx: index("messages_sender_idx").on(t.senderId),
  }),
);

/* --------------------------------------------------------------- reviews */

export const reviews = pgTable(
  "reviews",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contractId: uuid("contract_id")
      .notNull()
      .references(() => contracts.id, { onDelete: "cascade" }),
    authorId: uuid("author_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    subjectId: uuid("subject_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    direction: reviewDirectionEnum("direction").notNull(),
    rating: integer("rating").notNull(),
    comment: text("comment"),
    /** The review subject gets exactly one public right of reply. */
    responseText: text("response_text"),
    responseAt: timestamp("response_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    onePerContractAuthor: uniqueIndex("reviews_contract_author_unique").on(
      t.contractId,
      t.authorId,
    ),
    subjectIdx: index("reviews_subject_idx").on(t.subjectId),
    ratingRange: check("reviews_rating_range_check", sql`${t.rating} >= 1 and ${t.rating} <= 5`),
  }),
);

/* -------------------------------------------------- notifications & ops */

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    type: notificationTypeEnum("type").notNull(),
    title: varchar("title", { length: 160 }).notNull(),
    body: text("body"),
    link: text("link"),
    readAt: timestamp("read_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    userIdx: index("notifications_user_idx").on(t.userId),
    unreadIdx: index("notifications_unread_idx").on(t.userId, t.readAt),
  }),
);

export const disputes = pgTable(
  "disputes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    contractId: uuid("contract_id")
      .notNull()
      .references(() => contracts.id, { onDelete: "cascade" }),
    milestoneId: uuid("milestone_id").references(() => milestones.id, { onDelete: "set null" }),
    openedBy: uuid("opened_by")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    reason: text("reason").notNull(),
    status: disputeStatusEnum("status").notNull().default("OPEN"),
    resolutionNote: text("resolution_note"),
    resolvedBy: uuid("resolved_by").references(() => users.id, { onDelete: "set null" }),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    contractIdx: index("disputes_contract_idx").on(t.contractId),
    statusIdx: index("disputes_status_idx").on(t.status),
  }),
);

export const auditLogs = pgTable(
  "audit_logs",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    actorId: uuid("actor_id").references(() => users.id, { onDelete: "set null" }),
    action: varchar("action", { length: 80 }).notNull(),
    entityType: varchar("entity_type", { length: 60 }).notNull(),
    entityId: varchar("entity_id", { length: 80 }),
    meta: jsonb("meta"),
    ipAddress: varchar("ip_address", { length: 64 }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    actorIdx: index("audit_logs_actor_idx").on(t.actorId),
    entityIdx: index("audit_logs_entity_idx").on(t.entityType, t.entityId),
  }),
);

/* ------------------------------------------------------- files & uploads */

/**
 * Uploaded files live on disk (UPLOAD_DIR); this table is the metadata +
 * authorization record. An upload starts life unlinked (both FKs null) and is
 * bound to exactly one conversation message or escrow milestone when the post
 * it belongs to is submitted. Files whose context is PORTFOLIO and which are
 * still unlinked are treated as public imagery for a freelancer's profile.
 */
export const attachments = pgTable(
  "attachments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    uploaderId: uuid("uploader_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    context: attachmentContextEnum("context").notNull(),
    messageId: uuid("message_id").references(() => messages.id, { onDelete: "cascade" }),
    milestoneId: uuid("milestone_id").references(() => milestones.id, { onDelete: "cascade" }),
    /** Original client-side name, shown in the UI. */
    fileName: varchar("file_name", { length: 240 }).notNull(),
    /** Random on-disk name under UPLOAD_DIR — never derived from user input. */
    storageKey: varchar("storage_key", { length: 120 }).notNull(),
    mimeType: varchar("mime_type", { length: 120 }).notNull(),
    sizeBytes: integer("size_bytes").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    storageKeyUnique: uniqueIndex("attachments_storage_key_unique").on(t.storageKey),
    uploaderIdx: index("attachments_uploader_idx").on(t.uploaderId),
    messageIdx: index("attachments_message_idx").on(t.messageId),
    milestoneIdx: index("attachments_milestone_idx").on(t.milestoneId),
    positiveSize: check("attachments_size_positive_check", sql`${t.sizeBytes} > 0`),
  }),
);

/* ---------------------------------------------------- portfolio & saved */

/** A freelancer's showcase pieces, rendered on their public profile. */
export const portfolioItems = pgTable(
  "portfolio_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    freelancerId: uuid("freelancer_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    title: varchar("title", { length: 140 }).notNull(),
    description: text("description"),
    url: text("url"),
    /** Optional cover image uploaded through the attachment pipeline. */
    imageAttachmentId: uuid("image_attachment_id").references(() => attachments.id, {
      onDelete: "set null",
    }),
    position: integer("position").notNull().default(0),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    freelancerIdx: index("portfolio_items_freelancer_idx").on(t.freelancerId),
  }),
);

/** Freelancer bookmarks on open projects ("saved for later"). */
export const savedProjects = pgTable(
  "saved_projects",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: uuid("user_id")
      .notNull()
      .references(() => users.id, { onDelete: "cascade" }),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    onePerUserProject: uniqueIndex("saved_projects_user_project_unique").on(t.userId, t.projectId),
    userIdx: index("saved_projects_user_idx").on(t.userId),
    projectIdx: index("saved_projects_project_idx").on(t.projectId),
  }),
);

/* -------------------------------------------------------------- exports */

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type FreelancerProfile = typeof freelancerProfiles.$inferSelect;
export type ClientProfile = typeof clientProfiles.$inferSelect;
export type Project = typeof projects.$inferSelect;
export type Proposal = typeof proposals.$inferSelect;
export type Contract = typeof contracts.$inferSelect;
export type Milestone = typeof milestones.$inferSelect;
export type Review = typeof reviews.$inferSelect;
export type Notification = typeof notifications.$inferSelect;
export type Dispute = typeof disputes.$inferSelect;
export type UserRole = (typeof userRoleEnum.enumValues)[number];
export type ProjectStatus = (typeof projectStatusEnum.enumValues)[number];
export type ProposalStatus = (typeof proposalStatusEnum.enumValues)[number];
export type ContractStatus = (typeof contractStatusEnum.enumValues)[number];
export type MilestoneStatus = (typeof milestoneStatusEnum.enumValues)[number];
export type NotificationType = (typeof notificationTypeEnum.enumValues)[number];
export type Attachment = typeof attachments.$inferSelect;
export type AttachmentContext = (typeof attachmentContextEnum.enumValues)[number];
export type PortfolioItem = typeof portfolioItems.$inferSelect;
export type SavedProject = typeof savedProjects.$inferSelect;
export type DisputeStatus = (typeof disputeStatusEnum.enumValues)[number];
